services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/storage:/app/storage
      - ./backend/files.db:/app/files.db
    restart: unless-stopped
